name: 'Wodby deploy'
description: 'Handles a deploy on a Wodby app instance'
branding:
  icon: arrow-up-circle
  color: blue
inputs:
  uuid:
    description: 'Instance UUID (provided by Wodby)'
    required: true
  path:
    description: 'Base path to build'
    required: true
    default: './'
  dockerfile:
    description: 'Path to a custom Dockerfile (Will replace one provided by Wodby)'
    required: false
  create_env_symlink:
    description: 'Set to'
    required: false
  env_filepath:
    description: 'Path to a file which will be symlinked to a ${path}/.env file.'
    required: false
    default: '/mnt/files/keys/env_file'
runs:
  using: "composite"
  steps:
  -
    name: download wodby-cli pinned to 1.0.1
    run: |
      wget -qO- https://s3.amazonaws.com/wodby-releases/wodby-cli/1.0.1/linux/amd64/wodby-linux-amd64.tar.gz | sudo tar xz -C /usr/local/bin
    shell: bash
  -
    run: ${{ github.action_path }}/deploy.sh
    shell: bash
    env:
      INSTANCE_UUID: ${{ inputs.uuid }}
      BUILD_PATH: ${{ inputs.path }}
      CUSTOM_DOCKERFILE: ${{ inputs.dockerfile }}
      CREATE_ENV_SYMLINK: ${{ inputs.create_env_symlink }}
      ENV_FILEPATH: ${{ inputs.env_filepath }}
